stages:
  - build
  - lint
  - deploy

build-test:
  stage: build
  script:
    - echo "Compiling code"
    - echo "Building application"


lint-job:
  stage: lint
  image: node:latest
  script:
    - npm install eslint-plugin-react-hooks@latest --save-dev
    - npm install eslint-plugin-react@latest --save-dev
    - npm install --save-dev eslint
    - npx eslint .
    

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
